DeGuzman_LabAct/DeGuzman_LabAct/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using DeGuzman_LabAct.Models;
using DeGuzman_LabAct.Services;
using System.ComponentModel.DataAnnotations;
using DeGuzman_LabAct.Data;

namespace DeGuzman_LabAct.Controllers
{
    public class InstructorController : Controller
    {
        /*List<Instructor> InstructorList = new List<Instructor>
            {
                new Instructor()
                {
                    Id= 1,
                    FName = "Jason",
                    LName = "Beltran", 
                    Rank = Rank.Instructor, 
                    HiringDate = DateTime.Parse("2022-08-26"), 
                    IsTenured = true
                },
                new Instructor()
                {
                    Id= 2,
                    FName = "Manuel",
                    LName = "Barce", 
                    Rank = Rank.AssistantProfessor, 
                    HiringDate = DateTime.Parse("2022-08-07"), 
                    IsTenured = true
                },
                new Instructor()
                {
                    Id= 3,
                    FName = "Mikhail",
                    LName = "De Guzman", 
                    Rank = Rank.AssociateProfessor, 
                    HiringDate = DateTime.Parse("2020-01-25"), 
                    IsTenured = false
                },
                new Instructor()
                {
                    Id= 4,
                    FName = "Marie",
                    LName = "Ronquillo", 
                    Rank = Rank.Professor, 
                    HiringDate = DateTime.Parse("2019-01-25"), 
                    IsTenured = true
                }
            };*/
        private readonly AppDbContext _dbcontext;
        public InstructorController(AppDbContext dbContext)
        {
            _dbcontext = dbContext;
        }
        public IActionResult Index()
        {

            return View(_dbcontext.Instructors);
        }

        public IActionResult ShowDetail(int id)
        {
            //Search for the student whose id matches the given id
            Instructor? instructor = _dbcontext.Instructors.FirstOrDefault(st => st.Id == id);

            if (instructor != null)//was an student found?
                return View(instructor);

            return NotFound();
        }

        [HttpGet]
        public IActionResult AddInstructor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddInstructor(Instructor newInstructor)
        {
            if (!ModelState.IsValid)
                return View();
            _dbcontext.Instructors.Add(newInstructor);
            return RedirectToAction("Index");
        }

        public IActionResult EditInstructor()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditInstructor(int id)
        {
            Instructor? instructor = _dbcontext.Instructors.FirstOrDefault(ins => ins.Id == id);

            if (instructor != null)
                return View(instructor);

            return NotFound();
        }

        [HttpPost]
        public IActionResult EditInstructor(Instructor insInstructor)
        {
            var ins = _dbcontext.Instructors.FirstOrDefault(ins => ins.Id == insInstructor.Id);

            if (ins != null)
            {
                ins.Id = insInstructor.Id;
                ins.FName = insInstructor.FName;
                ins.LName = insInstructor.LName;
                ins.IsTenured = insInstructor.IsTenured;
                ins.Rank = insInstructor.Rank;
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult DeleteInstructor(int id)
        {
            Instructor? instructor = _dbcontext.Instructors.FirstOrDefault(instructor => instructor.Id == id);
            return View(instructor);
        }
        [HttpPost]
        public IActionResult DeleteInstructor(Instructor insInstructor)
        {
            var ins = _dbcontext.Instructors.FirstOrDefault(ins => ins.Id == insInstructor.Id);

            if (ins != null)
            {
                _dbcontext.Instructors.Remove(ins);
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DeGuzman_LabAct/DeGuzman_LabAct/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using DeGuzman_LabAct.Models;
using DeGuzman_LabAct.Services;
using DeGuzman_LabAct.Data;
using System;

namespace DeGuzman_LabAct.Controllers
{
    public class StudentController : Controller
    {
        /*List<Student> StudentList = new List<Student>
            {
                new Student()
                {
                    Id= 1,FirstName = "Gabriel",LastName = "Montano", Course = Course.BSIT, AdmissionDate = DateTime.Parse("2022-08-26"), GPA = 1.5, Email = "ghaby021@gmail.com"
                },
                new Student()
                {
                    Id= 2,FirstName = "Zyx",LastName = "Montano", Course = Course.BSIS, AdmissionDate = DateTime.Parse("2022-08-07"), GPA = 1, Email = "zyx@gmail.com"
                },
                new Student()
                {
                    Id= 3,FirstName = "Aerdriel",LastName = "Montano", Course = Course.BSCS, AdmissionDate = DateTime.Parse("2020-01-25"), GPA = 1.5, Email = "aerdriel@gmail.com"
                }
            };*/

        private readonly AppDbContext _dbContext;
        public StudentController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            
            return View(_dbContext.Roster);
        }

        public IActionResult ShowDetail(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = _dbContext.Roster.FirstOrDefault(st => st.Id == id);
            
            if (student != null)//was an student found?
                return View(student);

            return NotFound();
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddStudent(Student newStudent)
        {
            _dbContext.Roster.Add(newStudent);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult EditStudent()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditStudent(int id) 
        {
            Student? Student = _dbContext.Roster.FirstOrDefault(st => st.Id == id);

            if (Student != null)
                return View(Student);

            return NotFound();
        }

        [HttpPost]
        public IActionResult EditStudent(Student studentStudent)
        { 
            var st = _dbContext.Roster.FirstOrDefault(st => st.Id == studentStudent.Id);

            if (st != null)
            { 
                st.Id = studentStudent.Id;
                st.FirstName = studentStudent.FirstName;
                st.LastName = studentStudent.LastName;
                st.GPA = studentStudent.GPA;
                st.Course = studentStudent.Course;
                st.AdmissionDate = studentStudent.AdmissionDate;
                st.Email = studentStudent.Email;
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult DeleteStudent(int id)
        {
            Student? st = _dbContext.Roster.FirstOrDefault(st => st.Id == id);
            return View(st);
        }

        [HttpPost]
        public IActionResult DeleteStudent(Student insStudent)
        {
            var ins = _dbContext.Roster.FirstOrDefault(ins => ins.Id == insStudent.Id);

            if (ins != null)
            {
                _dbContext.Roster.Remove(ins);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

DeGuzman_LabAct/DeGuzman_LabAct/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeGuzman_LabAct</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeGuzman_LabAct.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeGuzman_LabAct</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor List</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Login" asp-controller="Account">Login</a>
                            </li>    
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Register" asp-controller="Account">Register new Account</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeGuzman_LabAct - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>